[libdefaults]
    default_realm = BRAINWARE-SOLUTIONS.DE
    dns_lookup_realm = false
    dns_lookup_kdc = false
    ticket_lifetime = 24h
    renew_lifetime = 7d
    forwardable = true
    rdns = false

[realms]
    BRAINWARE-SOLUTIONS.DE = {
        kdc = werk-2-vdcw2k22.brainware-solutions.de
        kdc = w2-vdc-2.brainware-solutions.de
        admin_server = werk-2-vdcw2k22.brainware-solutions.de
    }

[domain_realm]
    .brainware-solutions.de = BRAINWARE-SOLUTIONS.DE
    brainware-solutions.de = BRAINWARE-SOLUTIONS.DE
